
palette = [
    ('body', '', ''),
    ('session', '', ''),
    ('session_focus', '', '', '', 'g0', '#a8a'),
    ('folder', 'light blue,bold', ''),
    ('folder_focus', 'light blue,bold', '', '', 'g0', '#a8a'),
    ('head', 'yellow', 'black', 'standout'),
    ('foot', 'light gray', 'black'),
    ('key', 'light cyan', 'black', 'underline'),
    ('title', 'white', 'black', 'bold'),
    ('dirmark', 'black', 'dark cyan', 'bold'),
    ('flag', 'dark gray', 'light gray'),
    ('error', 'dark red', 'light gray'),
    ('fbutton', 'black', 'dark gray', '', 'g0', '#a8a'),
    ('fbutton_sc', 'dark red', 'black', 'bold', '#600', '#d86'),
    ('dialog', 'dark red', 'light blue', '', 'g0', '#a8a'),
    ('dialog_button', 'dark red', 'light blue', '', '#600', '#a8a'),
    ('dialog_button_focus', 'dark red', 'light blue', '', '#600', '#d86'),
]
